
development:
  adapter: sqlite3
  database: db/computer.sqlite3

test:
  adapter: sqlite3
  database: db/computer.sqlite3

production:
  adapter: mysql
  database: xadm
  username: "xadm_user"
  password: ""
  host: print-pool


