
development:
  adapter: sqlite3
  database: db/adm.sqlite3

test:
  adapter: sqlite3
  database: db/adm.sqlite3

production:
  adapter: mysql
  database: adm2
  username: "bibliothek"
  password: "pooluser"
  host: print-pool
